# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cdBoundary',
                'doc_host': 'https://civildot.github.io',
                'git_url': 'https://github.com/civildot/cdBoundary',
                'lib_path': 'cdBoundary'},
  'syms': {'cdBoundary.core': {'cdBoundary.core.foo': ('core.html#foo', 'cdBoundary/core.py')}}}
