# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fileio.ipynb.

# %% auto 0
__all__ = ['FileIO']

# %% ../nbs/01_fileio.ipynb 3
import fiona
from fiona import Geometry, Feature, Properties
from shapely.geometry import shape

from .boundary import ConcaveHull

# %% ../nbs/01_fileio.ipynb 7
class FileIO(ConcaveHull):

    def __init__(self, infile:str, inlayer: str=None):

        self.triangles = dict()
        self.tedges = list()
        self.elengths = list()
        self.maxtriangles = 0
        
        self.infile = infile
        self.inlayer = inlayer
        self.points = list()
        
        with fiona.open(infile, layer=inlayer) as source:
            for feat in source:
                # Todo: Support Z
                pt = shape(feat.geometry)
                if pt.geom_type == 'MultiPoint':
                    for item in list(pt.geoms):
                        self.points.append([item.x, item.y])
                elif pt.geom_type == 'Point':
                    self.points.append([pt.x, pt.y])
